import type { Metadata } from "next";
import "./globals.css";
import SidePanel from "./components/SidePanel"

export const metadata: Metadata = {
  title: "Task Manager",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className="w-full h-full antialiased dark">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Archivo:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
      </head>
      <body className="w-full h-full flex
        bg-linear-to-br gap-[24px]
        from-[var(--baby-blue)]
        to-[var(--white)]"
      >
        <SidePanel />
        <main className="w-full h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
